AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'sam-app-example

  Sample SAM Template for sam-app-example

  '
Globals:
  Function:
    Environment:
      Variables:
        TABLE_NAME:
          Ref: Table
    Timeout: 10
    Runtime: nodejs12.x
Resources:
  Table:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: User
      PrimaryKey:
        Name: userid
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://david-sam/74aa2aba0c769bbe54bda6370952802b
      Handler: app.lambdaHandler
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
  GetUser:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://david-sam/74aa2aba0c769bbe54bda6370952802b
      Handler: get.lambdaHandler
      Policies: AmazonDynamoDBReadOnlyAccess
      Events:
        GetUser:
          Type: Api
          Properties:
            Path: /user/{userid}
            Method: get
  PostUser:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://david-sam/74aa2aba0c769bbe54bda6370952802b
      Handler: post.lambdaHandler
      Policies: AmazonDynamoDBFullAccess
      Events:
        PostUser:
          Type: Api
          Properties:
            Path: /user/{userid}
            Method: post
  DeleteUser:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://david-sam/74aa2aba0c769bbe54bda6370952802b
      Handler: delete.lambdaHandler
      Policies: AmazonDynamoDBFullAccess
      Events:
        DeleteUser:
          Type: Api
          Properties:
            Path: /user/{userid}
            Method: delete
